import type { Metadata } from 'next';
import DocsDirectory from '@/components/community/DocsDirectory';
import { publishedGuides } from '@/lib/docs/library';

export const metadata: Metadata = { title: 'GiftGrid Docs', description: 'Practical guides for GiftGrid buyers, merchants, community members and developers.', alternates: { canonical: 'https://community.degiftgrid.com/docs' }, openGraph: { title: 'GiftGrid Docs', url: 'https://community.degiftgrid.com/docs', description: 'Learn how to source gifts, manage products and take part in the community.' } };
export default function DocsPage() {
  if (!publishedGuides.length) return <main className="mx-auto max-w-3xl px-5 py-14"><div className="rounded-2xl border border-slate-200 bg-white p-8"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">GiftGrid Docs</p><h1 className="mt-4 text-3xl font-bold text-slate-950">Our comprehensive guides are being prepared.</h1><p className="mt-5 text-base leading-8 text-slate-600">We are expanding the help centre to cover community participation, buyer sourcing, merchant products and developer tools. Each guide is checked before publication.</p><a href="/contact" className="mt-6 inline-block min-h-12 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Get help now</a></div></main>;
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="rounded-3xl bg-slate-950 px-6 py-9 text-white sm:px-10"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-300">The GiftGrid knowledge centre</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">A clear next step.</h1><p className="mt-4 max-w-2xl text-base leading-7 text-slate-200">Comprehensive guides for finding gifts, growing your merchant profile, joining conversations and building with GiftGrid.</p><p className="mt-6 text-sm text-blue-200">{publishedGuides.length} guides across accounts, community, sourcing, products and developer tools.</p></div><DocsDirectory guides={publishedGuides.map(({ slug, title, summary, category, wordCount }) => ({ slug, title, summary, category, wordCount }))} /></main>;
}
