import {createCipheriv,createDecipheriv,createHash,createHmac,randomBytes,timingSafeEqual} from 'node:crypto';
export function shopDomain(value:unknown){if(typeof value!=='string')throw Error('Enter your myshopify.com store address.');const shop=value.trim().toLowerCase().replace(/^https:\/\//,'').replace(/\/$/,'');if(!/^[a-z0-9][a-z0-9-]{0,62}\.myshopify\.com$/.test(shop))throw Error('Use your store-name.myshopify.com address.');return shop}
export const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
export const nonce=()=>randomBytes(32).toString('hex');
export function equal(a:string,b:string){const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)}
export function configuration(){const clientId=process.env.SHOPIFY_CLIENT_ID,secret=process.env.SHOPIFY_CLIENT_SECRET,key=process.env.SHOPIFY_TOKEN_ENCRYPTION_KEY,base=process.env.SHOPIFY_APP_URL,version=process.env.SHOPIFY_API_VERSION||'2026-07';if(!clientId||!secret||!key||!/^[a-f0-9]{64}$/i.test(key)||!base)throw Error('Shopify is not configured yet.');const url=new URL(base);if(url.protocol!=='https:'||url.pathname!=='/'||url.search||url.hash||url.username||url.password)throw Error('Set SHOPIFY_APP_URL to the HTTPS app origin.');if(!/^20\d{2}-(01|04|07|10)$/.test(version))throw Error('Invalid Shopify API version.');return {clientId,secret,key:Buffer.from(key,'hex'),origin:url.origin,version}}
export function configured(){try{configuration();return true}catch{return false}}
export function seal(value:string,shop:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',configuration().key,iv);cipher.setAAD(Buffer.from(shop));const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return ['v1',iv.toString('base64'),cipher.getAuthTag().toString('base64'),encrypted.toString('base64')].join('.')}
export function unseal(value:string,shop:string){const [version,iv,tag,data]=value.split('.');if(version!=='v1')throw Error('Unsupported token format.');const cipher=createDecipheriv('aes-256-gcm',configuration().key,Buffer.from(iv,'base64'));cipher.setAAD(Buffer.from(shop));cipher.setAuthTag(Buffer.from(tag,'base64'));return Buffer.concat([cipher.update(Buffer.from(data,'base64')),cipher.final()]).toString('utf8')}
export function validCallback(params:URLSearchParams){const names=[...params.keys()];if(new Set(names).size!==names.length)return false;const signature=params.get('hmac')||'';if(!/^[a-f0-9]{64}$/i.test(signature))return false;const timestamp=Number(params.get('timestamp'));if(!Number.isFinite(timestamp)||Math.abs(Date.now()/1000-timestamp)>600)return false;const message=[...params.entries()].filter(([key])=>key!=='hmac').sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>key+'='+value).join('&');return equal(createHmac('sha256',configuration().secret).update(message).digest('hex'),signature.toLowerCase())}
export function validWebhook(body:string,signature:string){return equal(createHmac('sha256',configuration().secret).update(body).digest('base64'),signature)}
export type ShopifyProduct={id:string;title:string;description:string;productType:string;status:string;onlineStoreUrl:string|null;totalInventory:number|null;featuredImage:{url:string}|null;priceRangeV2:{minVariantPrice:{amount:string;currencyCode:string};maxVariantPrice:{amount:string;currencyCode:string}}};
export function listingFromProduct(p:ShopifyProduct){const low=p.priceRangeV2.minVariantPrice,high=p.priceRangeV2.maxVariantPrice;return {id:p.id,title:p.title.slice(0,240),short_description:(p.description||p.title).slice(0,500),description:p.description.slice(0,20000),category:(p.productType||'Gifts').slice(0,120),hero_image_url:p.featuredImage?.url||null,price_range:low.currencyCode+' '+low.amount+(low.amount===high.amount?'':'–'+high.amount),available_quantity:p.totalInventory,status:p.status==='ACTIVE'&&!!p.onlineStoreUrl?'published':'archived'}}
