"use client";
import { FormEvent,useEffect,useState } from "react";
import Link from "next/link";
import { isGiftGridAdmin } from "@/config/identity";
import CountrySelect from "@/components/shared/CountrySelect";
import MediaUpload from "./MediaUpload";
export default function CommunityProfile(){
  const [role,setRole]=useState("");
  const [name,setName]=useState(""),[bio,setBio]=useState(""),[country,setCountry]=useState(""),[email,setEmail]=useState(""),[imagePath,setImagePath]=useState(""),[image,setImage]=useState(""),[message,setMessage]=useState("Loading your profile…"),[signedIn,setSignedIn]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;fetch("/api/community/profile").then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(active){setRole(data.role);setName(data.display_name || data.fullName || "");setBio(data.bio || "");setCountry(data.country || "");setEmail(data.email || "");setImage(data.avatar_url || "");setSignedIn(true);setMessage("");}}).catch(error=>{if(active)setMessage(error.message);});return()=>{active=false;};},[]);
  async function save(event:FormEvent){event.preventDefault();setBusy(true);try{const response=await fetch("/api/community/profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:name,bio,country,listed:true,imagePath:imagePath || undefined})});const data=await response.json();setMessage(response.ok ? "Your profile is saved." : data.error);}catch{setMessage("Unable to save. Please try again.");}finally{setBusy(false);}}
  return <div className="mx-auto max-w-2xl space-y-5">{message && <p role="status">{message}</p>}{signedIn ? <form onSubmit={save} className="space-y-5 rounded-xl bg-white p-6 shadow-sm"><p className="break-all text-sm text-slate-500">{email}</p>{image && <img src={image} alt="Your profile photo" className="size-24 rounded-full object-cover"/>}{isGiftGridAdmin(role) ? <p className="text-sm text-slate-500">GiftGrid admins use the GiftGrid logo as their profile photo.</p> : <MediaUpload onUploaded={(path,url)=>{setImagePath(path);setImage(url);}}/>}<label className="block font-semibold">Your name<input required maxLength={120} value={name} onChange={event=>setName(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 p-3"/></label><label className="block font-semibold">Introduction<textarea maxLength={1000} rows={5} value={bio} onChange={event=>setBio(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 p-3"/></label><label className="block font-semibold">Country<CountrySelect value={country} onChange={setCountry} /></label><p className="text-sm text-slate-500">Your public profile appears in the member directory. Your account email stays private.</p><button disabled={busy} className="rounded-lg bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-50">{busy ? "Saving…" : "Save profile"}</button></form> : <Link href="/auth/sign-in?next=/dashboard/profile" className="inline-block rounded-lg bg-blue-600 px-5 py-3 font-bold text-white">Sign in to edit your profile</Link>}</div>;
}
