"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useRef,useState } from "react";
type Conversation={id:string;requester_id:string;recipient_id:string;status:string;created_at:string};
type ChatMessage={id:string;sender_id:string;body:string;created_at:string};
type Person={id:string;full_name:string};
export default function MessageCenter(){
  const [conversations,setConversations]=useState<Conversation[]>([]),[people,setPeople]=useState<Person[]>([]),[me,setMe]=useState(""),[selected,setSelected]=useState(""),[items,setItems]=useState<ChatMessage[]>([]),[body,setBody]=useState(""),[notice,setNotice]=useState("Loading messages…"),[login,setLogin]=useState(false),[busy,setBusy]=useState(false);
  const endRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth"});},[items]);
  const load=useCallback(async()=>{try{const response=await fetch("/api/community/connections",{cache:"no-store"}),data=await response.json();if(!response.ok){setLogin(response.status===401);setNotice(data.error||"Unable to load messages.");return;}setLogin(false);setNotice("");setConversations(data.connections||[]);setPeople(data.people||[]);setMe(data.userId);const wanted=new URLSearchParams(window.location.search).get("conversation");if(wanted&&(data.connections||[]).some((item:Conversation)=>item.id===wanted&&item.status==="accepted"))setSelected(current=>current||wanted);}catch{setNotice("Unable to load messages.");}},[]);
  useEffect(()=>{const run=setTimeout(()=>{void load();},0);const timer=setInterval(load,20000);return()=>{clearTimeout(run);clearInterval(timer);};},[load]);
  const loadMessages=useCallback(async()=>{if(!selected)return;try{const response=await fetch(`/api/community/connections/${selected}/messages`,{cache:"no-store"}),data=await response.json();if(response.ok)setItems(data.messages||[]);else setNotice(data.error||"Unable to open conversation.");}catch{setNotice("Unable to load conversation.");}},[selected]);
  useEffect(()=>{const run=setTimeout(()=>{void loadMessages();},0);return()=>clearTimeout(run);},[loadMessages]);
  async function send(event:FormEvent){event.preventDefault();const value=body.trim();if(!value||busy)return;setBusy(true);try{const response=await fetch(`/api/community/connections/${selected}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:value})}),data=await response.json();if(!response.ok){setNotice(data.error||"Message was not sent.");return;}setBody("");setNotice("");setItems(current=>[...current,data.message]);}catch{setNotice("Message was not sent. Please try again.");}finally{setBusy(false);}}
  const active=conversations.filter(item=>item.status==="accepted");
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-8 sm:px-6"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-600">Community messages</p><h1 className="mt-2 text-3xl font-bold">Messages</h1><p className="mt-3 text-sm leading-7 text-slate-600">Start a conversation from Connect. Messages are visible only to the two participants.</p><Link href="/connect" className="mt-3 inline-block font-semibold text-blue-700 underline">Find people to follow</Link></div>{notice&&<p role="status" className="text-sm text-slate-600">{notice}{login&&<> <Link href="/auth/sign-in?next=/messages" className="font-bold text-blue-700 underline">Sign in</Link></>}</p>}<div className="grid min-h-[30rem] overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm md:grid-cols-[260px_minmax(0,1fr)]"><nav aria-label="Conversations" className="border-b border-slate-200 p-3 md:border-b-0 md:border-r"><h2 className="px-3 py-2 text-sm font-bold">Conversations</h2>{active.map(item=>{const other=item.requester_id===me?item.recipient_id:item.requester_id;return <button key={item.id} onClick={()=>{setSelected(item.id);setItems([]);}} className={`mb-1 w-full rounded-xl p-3 text-left text-sm ${selected===item.id?"bg-blue-50 text-blue-900":"hover:bg-slate-50"}`}><span className="block font-semibold">{people.find(person=>person.id===other)?.full_name||"GiftGrid member"}</span><span className="mt-1 block text-xs text-slate-500">Open conversation</span></button>;})}{!active.length&&!login&&<p className="px-3 py-3 text-sm text-slate-500">No conversations yet. Follow a member, then choose Message.</p>}</nav><section className="flex min-h-[26rem] min-w-0 flex-col p-4 sm:p-6" aria-label="Selected conversation">{selected&&active.some(item=>item.id===selected)?<><div className="flex-1 space-y-3 overflow-y-auto" aria-live="polite">{items.map(item=><div key={item.id} className={`max-w-[85%] rounded-xl p-3 ${item.sender_id===me?"ml-auto bg-blue-50":"bg-slate-100"}`}><p className="whitespace-pre-wrap break-words text-sm">{item.body}</p><time className="mt-2 block text-xs text-slate-500">{new Date(item.created_at).toLocaleString()}</time></div>)}<div ref={endRef}/></div><form onSubmit={send} className="mt-4 flex gap-2"><input aria-label="Write a message" required maxLength={5000} value={body} onChange={event=>setBody(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm" placeholder="Write a private message…"/><button disabled={busy||!body.trim()} aria-label="Send message" title="Send" className="flex items-center rounded-xl bg-blue-600 px-4 py-3 text-white disabled:opacity-50"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="size-5"><path d="M22 2 11 13M22 2l-7 20-4-9-9-4 20-7z"/></svg></button></form></>:<div className="m-auto text-center text-sm text-slate-500">Choose a conversation, or start one from a member profile.</div>}</section></div></main>;
}
