import Link from 'next/link';
import { requireSuperAdmin } from '@/lib/admin/require-super-admin';
import { createAdminClient } from '@/lib/supabase/admin';
import { getArticles } from '@/lib/blog/articles';
import { bloggerHosts } from '@/lib/blog/blogger';
import BlogPublishingControls from '@/components/admin/BlogPublishingControls';
export const metadata={title:'Blog publishing — GiftGrid Admin'};
export default async function AdminBlogPage({searchParams}:{searchParams:Promise<{error?:string;connected?:string}>}){
 await requireSuperAdmin();const params=await searchParams;const articles=await getArticles();let connections:{hostname:string;name:string}[]=[];let problem='';let publications:{slug:string;status:string;url:string|null;error:string|null}[]=[];
 try{const db=createAdminClient();const [c,p]=await Promise.all([db.from('blog_connections').select('hostname,name'),db.from('blog_publications').select('slug,status,url,error').order('updated_at',{ascending:false}).limit(20)]);connections=c.data||[];publications=p.data||[];if(c.error||p.error)problem='Apply the blog database migration to enable connections and the publishing queue.';}catch{problem='The server database connection is not configured.';}
 return <div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Editorial</p><h1 className="mt-3 text-3xl font-semibold">GiftGrid Journal</h1><p className="mt-3 text-slate-500">{articles.length} articles ready · Minimum 700 words · One daily publication to both Blogger destinations</p>{(params.error||problem)&&<p role="alert" className="my-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{params.error||problem}</p>}{params.connected&&<p role="status" className="my-5 text-sm text-emerald-700">Blogger connection saved. Connect another Google account if the second blog belongs to a different account.</p>}<div className="my-7 grid gap-4 md:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">degiftgrid.com</h2><p className="mt-2 text-sm text-emerald-700">GiftGrid article library</p></div>{bloggerHosts.map(host=><div key={host} className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-bold">{host}</h2><p className="mt-2 text-sm text-slate-500">{connections.some(c=>c.hostname===host)?'Connected':'Google authorization required'}</p></div>)}</div><BlogPublishingControls/><p className="mt-4 text-xs text-slate-500">Automatic publishing runs at 09:00 UTC when the scheduled job and Google connections are configured.</p><div className="mt-8 overflow-x-auto rounded-xl border border-slate-200 bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Article</th><th className="p-4">Topic</th><th className="p-4">Words</th><th className="p-4">Read</th></tr></thead><tbody>{articles.map(a=><tr key={a.slug} className="border-t border-slate-100"><td className="p-4 font-medium">{a.title}</td><td className="p-4">{a.category}</td><td className="p-4">{a.wordCount}</td><td className="p-4"><Link href={`/blog/${a.slug}`} className="text-blue-700">Preview ↗</Link></td></tr>)}</tbody></table></div>{publications.length>0&&<section className="mt-8"><h2 className="text-xl font-semibold">Recent deliveries</h2><div className="mt-4 space-y-3">{publications.map((p,i)=><div key={i} className="rounded-xl border border-slate-200 bg-white p-4 text-sm"><p className="font-semibold">{p.slug} · {p.status}</p>{p.url&&<a href={p.url} className="mt-2 block text-blue-700">Open Blogger post ↗</a>}{p.error&&<p className="mt-2 text-red-600">{p.error}</p>}</div>)}</div></section>}</div>;
}
