import React, {useCallback, useEffect, useMemo, useState} from 'react';
import {
  ActivityIndicator, Image, Pressable, RefreshControl, SafeAreaView,
  ScrollView, StatusBar, StyleSheet, Text, TextInput, View,
} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {createClient, processLock, SupabaseClient, Session} from '@supabase/supabase-js';
import 'react-native-url-polyfill/auto';
import {BuyerRequests} from './src/screens/BuyerRequests';

const ORIGIN = 'https://community.degiftgrid.com';
type Tab = 'Community'|'Shop'|'Members'|'Dashboard'|'Profile';
type Product = {id:string;title:string;short_description?:string;description?:string;category?:string;hero_image_url?:string|null;price_range?:string|null;minimum_order_quantity?:number|null;merchant_profiles?:{business_name:string}|null};
type Post = {id:string;author_name:string;author_avatar?:string|null;topic:string;body:string;image_url?:string|null;like_count?:number;comment_count?:number;liked?:boolean};
type Member = {profile_id:string;display_name:string;kind:string;country?:string|null;bio?:string|null;avatar_url?:string|null;trade_deck_visible?:boolean};
type ApiClient = {supabase:SupabaseClient;session:Session|null;request:(path:string,method?:string,body?:unknown)=>Promise<any>};

async function createApiClient():Promise<ApiClient> {
  const config=await fetch(ORIGIN+'/api/mobile/config').then(r=>{if(!r.ok)throw new Error('GiftGrid sign-in is temporarily unavailable.');return r.json();});
  const supabase=createClient(config.url,config.key,{auth:{storage:AsyncStorage,persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,lock:processLock}});
  const {data}=await supabase.auth.getSession();
  const request=async(path:string,method='GET',body?:unknown)=>{
    const {data:{session}}=await supabase.auth.getSession();
    const response=await fetch(ORIGIN+'/api'+path,{method,headers:{...(session?{Authorization:'Bearer '+session.access_token}:{}),...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});
    const result=await response.json().catch(()=>({error:'Unexpected response from GiftGrid.'}));
    if(!response.ok)throw new Error(result.error||'Request failed.');
    return result;
  };
  return {supabase,session:data.session,request};
}

export default function App(){
  const [client,setClient]=useState<ApiClient|null>(null),[session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[tab,setTab]=useState<Tab>('Community');
  useEffect(()=>{let active=true;createApiClient().then(c=>{if(active){setClient(c);setSession(c.session);c.supabase.auth.onAuthStateChange((_event,next)=>setSession(next));}}).catch(e=>setError(e.message));return()=>{active=false;};},[]);
  if(error&&!client)return <SafeAreaView style={s.center}><Text style={s.title}>GiftGrid</Text><Text style={s.muted}>{error}</Text><Action label="Try again" onPress={()=>{setError('');createApiClient().then(c=>{setClient(c);setSession(c.session);}).catch(e=>setError(e.message));}}/></SafeAreaView>;
  if(!client)return <SafeAreaView style={s.center}><ActivityIndicator color="#176b53"/><Text style={s.muted}>Connecting to GiftGrid…</Text></SafeAreaView>;
  return <SafeAreaView style={s.app}><StatusBar barStyle="dark-content" backgroundColor="#f5f7f6"/><View style={s.brand}><Text style={s.brandName}>GiftGrid</Text><Text style={s.brandTag}>Thoughtful business gifting</Text></View><View style={s.content}>{tab==='Community'?<Community client={client} session={session} onSignIn={()=>setTab('Profile')}/>:tab==='Shop'?<Shop client={client}/>:tab==='Members'?<Members client={client}/>:tab==='Dashboard'?<Dashboard client={client} session={session} onSignIn={()=>setTab('Profile')}/>:<Profile client={client} session={session} onSession={setSession}/>}</View><View style={s.tabs}>{(['Community','Shop','Members','Dashboard','Profile'] as Tab[]).map(t=><Pressable key={t} onPress={()=>setTab(t)} style={s.tab}><Text style={[s.tabText,tab===t&&s.tabActive]}>{t}</Text></Pressable>)}</View></SafeAreaView>;
}

function Community({client,session,onSignIn}:{client:ApiClient;session:Session|null;onSignIn:()=>void}){
  const [posts,setPosts]=useState<Post[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[commenting,setCommenting]=useState(''),[comment,setComment]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{setPosts((await client.request('/community/posts?limit=30')).posts||[]);setMessage('');}catch(e:any){setMessage(e.message);}finally{setLoading(false);}},[client]);
  useEffect(()=>{void load();},[load]);
  const publish=async()=>{if(!session)return onSignIn();if(!draft.trim())return;setBusy(true);try{await client.request('/community/posts','POST',{body:draft.trim(),topic:'General'});setDraft('');await load();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}};
  const like=async(post:Post)=>{if(!session)return onSignIn();try{const liked=!post.liked;setPosts(old=>old.map(p=>p.id===post.id?{...p,liked,like_count:(p.like_count||0)+(liked?1:-1)}:p));await client.request(`/community/posts/${post.id}/reactions`,'POST',{liked});}catch(e:any){setMessage(e.message);void load();}};
  const addComment=async(id:string)=>{if(!session)return onSignIn();if(!comment.trim())return;try{await client.request(`/community/posts/${id}/comments`,'POST',{body:comment.trim()});setComment('');setCommenting('');setMessage('Comment posted.');}catch(e:any){setMessage(e.message);}};
  return <ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#176b53"/>}><Text style={s.heading}>Community</Text><Text style={s.muted}>Meet buyers and merchants building better gifting programs.</Text>{session?<View style={s.card}><TextInput value={draft} onChangeText={setDraft} placeholder="Share a sourcing question or idea…" multiline style={[s.input,s.multiline]}/><Action label={busy?'Posting…':'Post'} onPress={publish} disabled={busy}/></View>:<View style={s.card}><Text style={s.body}>Sign in to like, comment, and share with the community.</Text><Action label="Sign in" onPress={onSignIn}/></View>}{!!message&&<Text style={s.notice}>{message}</Text>}{loading&&posts.length===0?<ActivityIndicator color="#176b53"/>:posts.map(p=><View style={s.card} key={p.id}><Text style={s.topic}>{p.topic||'Community'}</Text><Text style={s.author}>{p.author_name}</Text>{!!p.image_url&&<Image source={{uri:p.image_url}} style={s.postImage} resizeMode="cover"/>}<Text style={s.body}>{p.body}</Text><View style={s.actions}><Action label={`${p.liked?'♥':'♡'} ${p.like_count||0}`} onPress={()=>void like(p)}/><Action label={`Comment · ${p.comment_count||0}`} onPress={()=>setCommenting(commenting===p.id?'':p.id)}/></View>{commenting===p.id&&<View><TextInput value={comment} onChangeText={setComment} placeholder="Write a comment" style={s.input}/><Action label="Send comment" onPress={()=>void addComment(p.id)}/></View>}</View>)}<BuyerRequests client={client} session={session} onSignIn={onSignIn}/></ScrollView>;
}

function Shop({client}:{client:ApiClient}){
  const [products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState<Product|null>(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{setProducts((await client.request('/shop?page=1')).products||[]);setNotice('');}catch(e:any){setNotice(e.message);}finally{setLoading(false);}},[client]);useEffect(()=>{void load();},[load]);
  const open=async(p:Product)=>{setSelected(p);try{const data=await client.request(`/shop/${p.id}`);setSelected(data.product||p);}catch{setSelected(p);}};
  return <ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#176b53"/>}><Text style={s.heading}>{selected?'Product details':'GiftGrid Shop'}</Text>{selected?<><Action label="‹ Back to shop" onPress={()=>setSelected(null)}/>{selected.hero_image_url&&<Image source={{uri:selected.hero_image_url}} style={s.productImage} resizeMode="cover"/>}<Text style={s.title}>{selected.title}</Text><Text style={s.muted}>{selected.category}</Text><Text style={s.body}>{selected.description||selected.short_description}</Text><Text style={s.body}>Minimum order: {selected.minimum_order_quantity||'Contact supplier'}</Text><Text style={s.body}>Price: {selected.price_range||'Request a quote'}</Text></>:<><Text style={s.muted}>Browse products for corporate gifting, including supplier listings.</Text>{!!notice&&<Text style={s.notice}>{notice}</Text>}{loading&&products.length===0?<ActivityIndicator color="#176b53"/>:products.map(p=><Pressable key={p.id} style={s.card} onPress={()=>void open(p)}>{p.hero_image_url&&<Image source={{uri:p.hero_image_url}} style={s.productImage} resizeMode="cover"/>}<Text style={s.title}>{p.title}</Text><Text style={s.muted}>{p.category} · {p.price_range||'Request a quote'}</Text><Text style={s.body}>{p.short_description}</Text></Pressable>)}</>}</ScrollView>;
}

function Members({client}:{client:ApiClient}){const [members,setMembers]=useState<Member[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');useEffect(()=>{client.request('/community/members').then(r=>setMembers(r.members||[])).catch(e=>setNotice(e.message)).finally(()=>setLoading(false));},[client]);const filtered=useMemo(()=>members.filter(m=>`${m.display_name} ${m.kind} ${m.country||''}`.toLowerCase().includes(query.toLowerCase())),[members,query]);return <ScrollView contentContainerStyle={s.page}><Text style={s.heading}>Members</Text><Text style={s.muted}>Discover buyers and merchants on GiftGrid.</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search members" style={s.input}/>{!!notice&&<Text style={s.notice}>{notice}</Text>}{loading?<ActivityIndicator color="#176b53"/>:filtered.map(m=><View style={s.card} key={m.profile_id}>{m.avatar_url&&<Image source={{uri:m.avatar_url}} style={s.avatar}/>}<Text style={s.title}>{m.display_name}</Text><Text style={s.muted}>{m.kind} · {m.country||'GiftGrid member'}</Text>{!!m.bio&&<Text style={s.body}>{m.bio}</Text>}</View>)}</ScrollView>}

function Dashboard({client,session,onSignIn}:{client:ApiClient;session:Session|null;onSignIn:()=>void}){const [info,setInfo]=useState<any>(null),[notice,setNotice]=useState('');useEffect(()=>{if(session)client.request('/merchant/profile').then(setInfo).catch(e=>setNotice(e.message));},[client,session]);if(!session)return <View style={s.page}><Text style={s.heading}>Dashboard</Text><Text style={s.body}>Sign in to access your GiftGrid workspace.</Text><Action label="Sign in" onPress={onSignIn}/></View>;return <ScrollView contentContainerStyle={s.page}><Text style={s.heading}>Dashboard</Text><Text style={s.muted}>Your GiftGrid workspace</Text>{!!notice&&<Text style={s.notice}>{notice}</Text>}<View style={s.card}><Text style={s.label}>Account</Text><Text style={s.body}>{session.user.email}</Text><Text style={s.muted}>{info?.business_name||info?.merchant?.business_name||'Complete your merchant profile to get started.'}</Text></View><View style={s.card}><Text style={s.label}>Trade deck</Text><Text style={s.body}>View your merchant documents securely from your GiftGrid profile.</Text></View></ScrollView>}

function Profile({client,session,onSession}:{client:ApiClient;session:Session|null;onSession:(v:Session|null)=>void}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const signIn=async()=>{setBusy(true);setNotice('');const {data,error}=await client.supabase.auth.signInWithPassword({email:email.trim(),password});if(error)setNotice(error.message);else{onSession(data.session);setNotice('Signed in successfully.');}setBusy(false);};const signOut=async()=>{await client.supabase.auth.signOut();onSession(null);};return <ScrollView contentContainerStyle={s.page}><Text style={s.heading}>Profile</Text>{session?<><View style={s.card}><Text style={s.label}>Signed in as</Text><Text style={s.body}>{session.user.email}</Text></View><Action label="Sign out" onPress={()=>void signOut()}/></>:<View style={s.card}><Text style={s.title}>Sign in to GiftGrid</Text><Text style={s.muted}>Use your existing GiftGrid account.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Email address" autoCapitalize="none" keyboardType="email-address" style={s.input}/><TextInput value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry style={s.input}/><Action label={busy?'Signing in…':'Sign in'} onPress={()=>void signIn()} disabled={busy}/><Text style={s.muted}>Create an account at community.degiftgrid.com to join GiftGrid.</Text></View>}{!!notice&&<Text style={s.notice}>{notice}</Text>}</ScrollView>}

function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={({pressed})=>[s.button,pressed&&s.pressed,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}
const s=StyleSheet.create({app:{flex:1,backgroundColor:'#f5f7f6'},content:{flex:1},brand:{paddingHorizontal:20,paddingTop:10,paddingBottom:9,borderBottomWidth:1,borderColor:'#e4eae7',backgroundColor:'#fff'},brandName:{fontSize:20,fontWeight:'800',color:'#176b53'},brandTag:{fontSize:11,color:'#718078',marginTop:1},tabs:{flexDirection:'row',backgroundColor:'#fff',borderTopWidth:1,borderColor:'#e4eae7',paddingBottom:5},tab:{flex:1,alignItems:'center',paddingVertical:14},tabText:{fontSize:10,color:'#64746c',fontWeight:'600'},tabActive:{color:'#176b53',fontWeight:'800'},page:{padding:16,paddingBottom:32,gap:12},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24,gap:14,backgroundColor:'#f5f7f6'},heading:{fontSize:24,fontWeight:'800',color:'#15251e'},title:{fontSize:18,fontWeight:'700',color:'#15251e'},label:{fontSize:14,fontWeight:'700',color:'#15251e'},author:{fontSize:14,fontWeight:'700',color:'#415349',marginTop:8},topic:{fontSize:11,fontWeight:'700',textTransform:'uppercase',color:'#176b53'},body:{fontSize:14,lineHeight:21,color:'#263b30',marginTop:8},muted:{fontSize:12,lineHeight:18,color:'#718078',marginTop:4},card:{backgroundColor:'#fff',borderRadius:14,padding:15,borderWidth:1,borderColor:'#e4eae7',gap:8},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d8e2dd',borderRadius:10,paddingHorizontal:12,paddingVertical:11,color:'#15251e',marginTop:8},multiline:{minHeight:76,textAlignVertical:'top'},button:{alignSelf:'flex-start',paddingHorizontal:14,paddingVertical:9,borderRadius:9,backgroundColor:'#176b53',marginTop:7},buttonText:{color:'#fff',fontSize:13,fontWeight:'700'},pressed:{opacity:.75},disabled:{opacity:.55},actions:{flexDirection:'row',gap:10,flexWrap:'wrap'},postImage:{width:'100%',height:210,borderRadius:10,marginTop:8},productImage:{width:'100%',height:190,borderRadius:10},avatar:{width:48,height:48,borderRadius:24},notice:{fontSize:13,color:'#8b4c14',padding:10,backgroundColor:'#fff3df',borderRadius:9}});
