'use client';
import { useMemo,useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import type { BlogArticle } from '@/lib/blog/types';
type Summary=Omit<BlogArticle,'sections'|'intro'>;
export default function BlogExplorer({articles}:{articles:Summary[]}){
 const [query,setQuery]=useState('');const [category,setCategory]=useState('All');const [page,setPage]=useState(1);
 const categories=['All',...new Set(articles.map(a=>a.category))];const filtered=useMemo(()=>articles.filter(a=>(category==='All'||a.category===category)&&`${a.title} ${a.excerpt} ${a.category}`.toLowerCase().includes(query.toLowerCase())),[articles,query,category]);const count=Math.ceil(filtered.length/9);
 return <section className="mx-auto max-w-7xl px-6 py-14 lg:px-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-700">The reading room</p><h2 className="mt-3 text-3xl font-semibold text-slate-950">Practical ideas. Clear next steps.</h2></div><label className="block text-xs font-semibold text-slate-600">Search articles<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Try packaging or store review" className="mt-2 block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm sm:w-72"/></label></div><div className="my-8 flex flex-wrap gap-2" aria-label="Filter by topic">{categories.map(c=><button key={c} type="button" aria-pressed={category===c} onClick={()=>{setCategory(c);setPage(1);}} className={`border px-4 py-2 text-xs font-semibold ${category===c?'border-blue-600 bg-blue-600 text-white':'border-slate-200 bg-white text-slate-600'}`}>{c}</button>)}</div><p role="status" className="mb-5 text-sm text-slate-500">{filtered.length} {filtered.length===1?'article':'articles'}</p><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.slice((page-1)*9,page*9).map(a=><article key={a.slug} className="group overflow-hidden rounded-2xl border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-lg"><Link href={`/blog/${a.slug}`} className="block"><div className="relative aspect-[16/10] overflow-hidden"><Image src={a.image} alt={a.imageAlt} fill sizes="(max-width:768px) 100vw,(max-width:1024px) 50vw,33vw" className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-6"><p className="text-xs font-semibold uppercase tracking-wider text-blue-700">{a.category} · {Math.ceil(a.wordCount/220)} min read</p><h3 className="mt-4 text-xl font-semibold leading-snug text-slate-950">{a.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{a.excerpt}</p><span className="mt-5 inline-block text-sm font-semibold text-blue-700">Read the guide ↗</span></div></Link></article>)}</div>{!filtered.length&&<p className="py-12 text-center text-slate-500">No articles match this search. Try another topic.</p>}{count>1&&<nav aria-label="Article pages" className="mt-10 flex justify-center gap-2">{Array.from({length:count},(_,i)=>i+1).map(n=><button key={n} aria-current={page===n?'page':undefined} onClick={()=>setPage(n)} className={`h-10 w-10 border text-sm font-semibold ${page===n?'bg-slate-950 text-white':'bg-white text-slate-700'}`}>{n}</button>)}</nav>}</section>;
}
