import { validateArticle,type BlogArticle } from './types';
export async function generateBlogArticle(topic:{slug:string;title:string;category:string;angle:string}):Promise<BlogArticle>{
 const local=process.env.LOCAL_AI_BASE_URL?.replace(/\/$/,'');
 const key=local?(process.env.LOCAL_AI_API_KEY||'local'):process.env.GROQ_API_KEY;
 if(!key||key.includes('SENSITIVE'))throw new Error('The article generation key is not configured.');
 const response=await fetch(local?`${local}/v1/chat/completions`:'https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:local?(process.env.LOCAL_AI_MODEL||'qwen2.5:3b'):(process.env.GROQ_MODEL||'openai/gpt-oss-20b'),temperature:.5,reasoning_effort:'low',max_completion_tokens:5000,response_format:{type:'json_object'},messages:[{role:'system',content:'Write practical, original ecommerce education. Return valid JSON. Never invent statistics, sources, customer stories, integrations, certifications, fees, guarantees or services.'},{role:'user',content:`Write a complete 950-1150 word article titled "${topic.title}" about ${topic.angle}. Category: ${topic.category}. At least 700 words of body text are mandatory. GiftGrid helps merchants maintain profiles, organize documents, messages and applications, and prepare for commercial opportunities. Buyers can submit sourcing requests; visitors can contact the team. Do not claim guaranteed sales, automatic matching, logistics services or unverified partners. Explain suggested workflows as advice, not as existing automated product features. Use a clearly hypothetical worked example, useful specifics and 6-8 sections, each with two substantial paragraphs. Avoid medical/legal/financial advice, unverified platform-specific instructions and padding. JSON shape: {"title":"string","excerpt":"short summary","intro":"paragraph","sections":[{"heading":"heading","paragraphs":["paragraph","paragraph"]}]}. No HTML or markdown.`}]}),signal:AbortSignal.timeout(150000)});
 if(!response.ok)throw new Error(`Article generation failed (${response.status}).`);const data=await response.json();const generated=JSON.parse(data.choices?.[0]?.message?.content||'{}');
 return validateArticle({...generated,slug:topic.slug,category:topic.category,date:new Date().toISOString().slice(0,10),image:'/images/heroes/merchant-studio.webp',imageAlt:'Product and packaging samples in a merchant studio'});
}

export async function planNextArticle(existingTitles:string[]){
 const local=process.env.LOCAL_AI_BASE_URL?.replace(/\/$/,'');
 const key=local?(process.env.LOCAL_AI_API_KEY||'local'):process.env.GROQ_API_KEY;if(!key)throw new Error('The article generation key is not configured.');
 const response=await fetch(local?`${local}/v1/chat/completions`:'https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:local?(process.env.LOCAL_AI_MODEL||'qwen2.5:3b'):(process.env.GROQ_MODEL||'openai/gpt-oss-20b'),temperature:.7,max_completion_tokens:1500,response_format:{type:'json_object'},messages:[{role:'system',content:'You plan useful, distinct ecommerce educational articles. Return JSON only.'},{role:'user',content:`Suggest ONE specific new GiftGrid Journal article about merchant readiness, product presentation, gifting operations, buyer briefs or merchant collaboration. It must address a different practical problem from existing articles, not rephrase an existing title. Avoid news, legal, medical, financial advice, software tutorials or unsupported GiftGrid feature claims. Existing titles: ${JSON.stringify(existingTitles.slice(-300))}. Return {"title":"clear reader-facing title without a date","category":"Readiness|Operations|Buyers|Products|GiftGrid|Brand building","angle":"a precise paragraph describing the distinct question, concrete example and useful takeaway"}.`}]}),signal:AbortSignal.timeout(45000)});
 if(!response.ok)throw new Error(`Article planning failed (${response.status}).`);const data=await response.json();const topic=JSON.parse(data.choices?.[0]?.message?.content||'{}');if(typeof topic.title!=='string'||typeof topic.angle!=='string'||typeof topic.category!=='string'||existingTitles.some(t=>t.toLowerCase()===topic.title.toLowerCase()))throw new Error('A distinct article topic could not be planned.');return topic as {title:string;category:string;angle:string};
}
