import { NextResponse } from 'next/server';
import { timingSafeEqual } from 'node:crypto';
import { getCommunityGuide } from '@/lib/docs/community-docs';
import { validateDocArticle } from '@/lib/docs/article';
import { writeDocJson } from '@/lib/docs/writer';

export const maxDuration = 180;
export async function POST(request: Request) {
  const expected = process.env.GIFTGRID_DOCS_BUILD_TOKEN;
  const provided = request.headers.get('authorization')?.replace(/^Bearer /, '') || '';
  if (!expected || Buffer.byteLength(provided) !== Buffer.byteLength(expected) || !timingSafeEqual(Buffer.from(provided), Buffer.from(expected))) return NextResponse.json({ error: 'Forbidden.' }, { status: 403 });
  let input;
  try { input = await request.json(); } catch { return NextResponse.json({ error: 'Invalid request.' }, { status: 400 }); }
  const guide = getCommunityGuide(typeof input?.slug === 'string' ? input.slug : '');
  if (!guide) return NextResponse.json({ error: 'Unknown guide.' }, { status: 404 });
  if (!(process.env.GROQ_API_KEY || process.env.CEREBRAS_API_KEY || process.env.GEMINI_API_KEY)) return NextResponse.json({ error: 'Writing provider unavailable.' }, { status: 503 });
  const facts = `GiftGrid is at community.degiftgrid.com; community.giftgrid.com is an alternate community hostname. Docs are /docs. Active accounts appear in the Members directory even with incomplete business profiles. Merchant product visibility is based on listing review and publication status, not document upload. Sign-in /auth/sign-in starts with buyer and merchant choice cards; saved role still controls access. Signup /auth/join. Password reset /auth/forgot-password. Public profiles /merchant/{id} and /members/{id}. Public posts, comments, counts; signed-in writes only. Posts max 2000 characters, comments max1500. One saved like per member and post; Like/Liked toggles it. Signed-in members can follow/unfollow active members from /connect or /merchants. Signed-in members can start private conversations from member cards and send messages at /messages; conversation contents are visible only to participants. Never expose account email in public profile, member directory, posts, or merchant cards. Merchant /dashboard/listings, /dashboard/workflow. Buyer /dashboard. Products are enquiry-based; external catalog entries identify AliExpress or Faire and link to supplier websites. No supplier stock has been imported yet. No checkout, payment processing, shipping, escrow, guaranteed sales, automated matching, verified partner contracts, or global supplier API. External entries older than seven days or known out-of-stock are hidden. Unknown prices/stock stay unknown. No guarantee a visible product is available. Console /console manages app records, scoped API keys and webhook REGISTRATION ONLY, no event delivery. No isolated sandbox, published rate-limit quotas or /api/v1 endpoints. Public GET /api/health, /api/shop?category=&page=, /api/community/posts. Protected /api/developer/apps GET POST; /api/developer/apps/{id}/keys POST; /api/developer/keys/{id} DELETE; /api/developer/apps/{id}/webhooks POST. Bearer API keys from environment, scopes apps:read apps:write keys:write webhooks:write. CLI in repository: npm run giftgrid -- status; shop list [--category value] [--page number]; community list; apps list; environment GIFTGRID_API_KEY, GIFTGRID_API_URL defaults https://www.degiftgrid.com/api. No public instructions about automated community publishing. Native app release not yet verified; never claim it is downloadable. Support /contact. No guaranteed support response times. No invented UI controls for reporting, exports, bulk invites, payments or privacy settings. Do not claim notification-email delivery is guaranteed.`;
  const corrections = `IMPORTANT UI FACTS: Human readers open / or /community for the feed, /market for products, /connect for following members, /merchants for merchant directory, /messages for private conversations, /merchant/{id} for public merchant profiles. Member account emails are private and must never appear on public pages or posts. /api paths return developer JSON, NOT web pages. Nondeveloper guides must not mention API paths, keys, developer console, CLI or automation. Signing in sends buyers and merchants to /dashboard (or a safe requested page). There is NO feed keyword/hashtag search, no product comments, no profile comments, no product reviews, no star ratings, no reporting/flagging button, no stock reservation. Only community POSTS have comments. Follow and private messaging controls require sign-in; conversation content is private to its participants. Community posts and comments are for relevant public discussion. Product enquiry action is Request a quote, not an instant order. External suppliers are not necessarily registered GiftGrid merchants, and their external cards lead to the supplier, not a GiftGrid conversation. Only EXTERNAL imported products have the seven-day freshness rule. Public endpoints do NOT require API keys. CLI status checks service health, not API key validity. No promised 48-hour or other response time. No account needed just to read public pages. Browsing does not reserve, order or pay. All uncertain capabilities must be omitted rather than assumed.`;
  const reviewing = input?.mode === 'review';
  const correcting = input?.mode === 'correct';
  if ((reviewing || correcting) && (!input.article || JSON.stringify(input.article).length > 45000)) return NextResponse.json({ error: 'Invalid review input.' }, { status: 400 });
  const prompt = reviewing
    ? `Fact-check and edit-review this draft against ONLY the verified implementation below. Return JSON {"approved":boolean,"issues":["specific correction needed"]}. Reject invented UI controls/routes, unsupported capabilities, API routes presented as web pages, wrong authentication rules, guarantees, misleading examples, repetition, irrelevant sections, or unlabelled hypothetical scenarios. Do not penalise practical advice clearly identified as an offline suggestion. Topic ${guide.title}; scope ${guide.summary}. VERIFIED FACTS: ${facts}\n${corrections}\nDRAFT: ${JSON.stringify(input.article)}`
    : correcting ? `Revise this existing help guide by applying the review corrections exactly. Preserve accurate sections and its subject, while removing unsupported claims. Keep at least 1100 words of substantive BODY PROSE, six to twelve sections, one or more substantial paragraphs each. Do not introduce new interface controls or features. Guidance about notes/checklists must explicitly be offline suggestions, never built-in tools. Return the COMPLETE corrected article as JSON {"intro":"...","sections":[{"heading":"...","paragraphs":["...","..."]}]}, no Markdown. VERIFIED FACTS: ${facts}\n${corrections}\nCORRECTIONS: ${String(input.feedback || '').slice(0, 5000)}\nDRAFT: ${JSON.stringify(input.article)}`
    : `Write an original comprehensive help guide, 1250â€“1550 words of BODY PROSE (minimum 1100), for the title "${guide.title}" in "${guide.category}". Stay tightly focused on this topic: ${guide.summary} Concrete workflow: ${guide.steps.join(' ')} Category context: ${guide.context}\nVERIFIED PRODUCT FACTS: ${facts}\n${corrections}\n${typeof input.feedback === 'string' ? 'Previous draft corrections to apply: ' + input.feedback.slice(0, 2500) : ''}\nExplain the specific task, decisions, expected outcomes, one detailed clearly hypothetical worked example, realistic failure cases and recovery, and a useful final verification process. Use 8 descriptive sections of two substantial paragraphs each plus an introduction. Make every section distinct and useful. For a simple button task, expand into relevant multi-device/session/retry troubleshooting and a realistic community workflow without repeating definitions. Guidance about organising work offline must be identified as suggested practice, not built-in features. Do not invent UI names, API routes, guarantees, fees, partners, statistics, customer stories or product capabilities. No legal, medical, tax or financial advice. Do not include external quotations. Never repeat generic paragraphs across sections. No filler to meet word count. No Markdown or HTML. Return JSON only: {"intro":"...","sections":[{"heading":"...","paragraphs":["...","..."]}]}.`;
  try {
    const generated = await writeDocJson(prompt, reviewing);
    if (reviewing) return NextResponse.json({ approved: generated.approved === true && Array.isArray(generated.issues) && generated.issues.length === 0, issues: Array.isArray(generated.issues) ? generated.issues.slice(0, 12) : ['Review did not return a valid assessment.'] }, { headers: { 'Cache-Control': 'private, no-store' } });
    const article = validateDocArticle(generated.article || generated, guide.slug);
    return NextResponse.json({ article }, { headers: { 'Cache-Control': 'private, no-store' } });
  } catch (error) {
    const message = error instanceof Error && /Guide has|Invalid guide|Repeated paragraph|Unsupported markup|^Writing providers unavailable:/.test(error.message) ? error.message : 'Guide generation failed.';
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
