export type Guide = { slug: string; title: string; summary: string; steps: string[]; category: string; destination: string; context: string };
type Section = { title: string; destination: string; context: string; guides: Guide[] };
function section(title: string, destination: string, context: string, rows: string): Section {
  return { title, destination, context, guides: rows.trim().split('\n').map(row => {
    const [name, summary, ...steps] = row.split('|');
    const slug = `${title}-${name}`.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-$/, '');
    return { slug, title: name, summary, steps, category: title, destination, context };
  }) };
}

export const docSections: Section[] = [
section('Getting started', '/auth/join', 'GiftGrid connects gifting buyers and merchants. Community membership, merchant product eligibility, and external supplier purchases are separate. Browsing a product does not reserve stock or place an order.', `
What GiftGrid does|Use the community to discover people and discuss corporate gifting.|Browse the feed for current conversations.|Explore the Market for product information.|Contact a merchant or visit the named supplier before committing to a purchase.
Your first visit|You can explore the community before creating an account.|Open Home to read published posts.|Visit Connect to browse members.|Sign in when you want to like, comment, follow, or message.
Choose your account|Choose the role that matches your main activity.|Choose buyer if you are sourcing gifts.|Choose merchant if you offer products.|Use your existing account instead of registering twice.
Join as a buyer|A buyer account helps you participate in sourcing conversations.|Select buyer on the join page.|Complete the buyer application with your own details.|Follow any email confirmation instructions before signing in.
Join as a merchant|You can create your merchant account before uploading a trade deck.|Choose merchant on the join page.|Complete registration and confirm your email when requested.|Add business information and your deck from your profile.
Find your workspace|The saved account role determines the workspace you can access.|Sign in with your registered email.|Use Dashboard for your account tools.|Use Profile to update your public introduction.
Understand the community|Posts are public conversations, while direct messages have their own access controls.|Read a few posts before contributing.|Use comments for information useful to other readers.|Move recipient details and quotations into private discussions.
Explore the shop|Shop cards introduce products rather than guarantee availability.|Choose a category relevant to your project.|Open a product to read its source and description.|Confirm stock, quantity, and delivery with the seller.
Meet merchants|The merchant directory includes members who are still preparing their business information.|Open Merchants from the community navigation.|Read a merchant profile and its deck status.|Ask specific questions before relying on a capability claim.
Meet buyers|Connect includes buyers as well as merchants.|Search for a name or location.|Read the person's introduction.|Send a relevant message that explains why you are reaching out.
Make your first post|A useful introduction explains your purpose and invites a specific response.|Introduce your business or sourcing need.|Include a relevant category and practical details.|Check the public text before publishing.
Your first sourcing brief|A short brief helps merchants answer with suitable options.|State the intended recipients and occasion.|Include quantity, destination, and required arrival date.|Ask suppliers to confirm price, stock, and any customisation separately.
Your first product listing|Prepare enough information for a buyer to understand the offer.|Use an accurate title and description.|Add a product image you are allowed to use.|Review the listing status and your trade-deck requirement.
Read member profiles|A visible account is not the same thing as an approved product.|Read the person's name, introduction, and business information.|Open a merchant product and request a quote to view its approved trade deck.|Confirm commercial details directly before ordering.
Public and private information|Decide what belongs in a public conversation before sharing.|Keep delivery addresses and employee lists out of posts.|Use a business introduction rather than private notes in your profile.|Review PDFs for personal information before uploading.
Use GiftGrid on a phone|The community navigation adapts to smaller screens.|Use the bottom navigation to move between sections.|Tap a product or profile for full details.|Keep the browser open until an upload confirms success.
Return to a conversation|Use a clear reference when continuing an earlier discussion.|Save the post link with Share.|Open Messages for private conversations.|Mention the product or brief when following up.
Get help getting started|A precise description makes a problem easier to investigate.|Record the page and action that failed.|Keep any visible error message.|Use Get help without sending passwords or API keys.
`),
section('Accounts', '/auth/sign-in', 'The account choice screen helps you reach the right form. It does not change your stored role or grant administrator access. Use your own account and keep sign-in details private.', `
Sign in|Sign in using the email attached to your existing account.|Choose buyer or merchant to open the form.|Enter your email and password.|Wait for your workspace to load before trying again.
Switch the sign-in choice|The Change control lets you return to the role choices.|Open the sign-in form.|Choose Change if you selected the wrong card.|Select the appropriate card and continue.
Show your password|The password visibility control can help you check typing mistakes.|Enter your password on a private screen.|Use Show password to inspect it.|Hide it again before someone else can see your screen.
Confirm your email|Some registrations require verification before a session is available.|Check the inbox used during registration.|Open the GiftGrid confirmation message and follow its link.|Return to sign-in if the registration screen asks you to do so.
Missing confirmation email|A missing message does not mean you should create several accounts.|Check spelling, spam, and filtered folders.|Allow a little time for delivery.|Contact support if you still cannot confirm the original account.
Forgotten password|Use the reset flow for the registered email.|Open Forgot password from sign-in.|Request the reset message for your account.|Follow the link and set a new password before returning.
Choose a password|Use a password unique to GiftGrid.|Create a long password with your password manager.|Avoid names, dates, and reused passwords.|Save it privately instead of including it in a support message.
Sign out|End your session when you finish on a shared device.|Save any work you want to keep.|Use the account sign-out control.|Confirm you return to a signed-out view.
Use a shared device|Keep another person's browser session separate from yours.|Check which account is currently signed in.|Sign out before signing in as yourself.|Do not save your password on an untrusted device.
Wrong workspace|The account record determines which dashboard opens.|Check that you used the intended email.|Sign out if another person's session was active.|Ask support about an incorrect saved role instead of creating duplicates.
Buyer versus merchant access|Buyer and merchant tools serve different workflows.|Use buyer tools to organise sourcing requests.|Use merchant tools for your business and listings.|Do not assume choosing a different sign-in card changes permissions.
Team sign-in|GiftGrid team and developer accounts have a separate entry to the same authentication form.|Choose the team or developer sign-in link.|Use your existing credentials.|Your saved role controls the destination and available tools.
Account without a trade deck|You can create your account before uploading the deck.|Create your account normally.|Complete the public introduction you want others to see.|Add the deck when ready and check product eligibility separately.
Account visibility|Active registered members appear in the community directory.|Review your displayed name and photo.|Check your public profile from Connect.|Remember that business approval and deck status do not hide your membership.
Protect account email|Your login email should not become your public introduction.|Use a name or business name as your display name.|Do not copy account emails into public posts by default.|Only include contact details in a public deck if you intend to share them.
Account loading errors|A failed workspace load can happen after authentication succeeds.|Read whether the message says you are already signed in.|Retry the page once after checking your connection.|Contact support with the route and error if it persists.
Expired session|An expired session can interrupt a like, comment, or upload.|Use the sign-in link shown by the action.|Return to the original page after signing in.|Check whether the action saved before repeating it.
Account changes and support|Some account changes require assistance rather than a public profile edit.|Identify whether you need a display-name change or account-access help.|Use Profile for public information.|Contact support for account changes that have no available control.
`),
section('Profiles', '/dashboard/profile', 'Public profiles introduce community members. Buyers do not need merchant trade decks. Merchant profiles remain discoverable while business details or decks are incomplete. Review the public result after saving.', `
Edit your introduction|Tell people what you offer or what you are looking for.|Open Profile while signed in.|Write a concise introduction with relevant experience.|Save and check the public profile.
Choose a display name|Use a recognisable name that does not expose your login address.|Use your name or a legitimate business identity.|Check spelling and unnecessary contact information.|Save before sharing your profile link.
Add a profile photo|A clear picture helps people recognise your account.|Choose a picture you own or may use.|Upload through the profile photo control.|Check the crop and resulting public image.
Choose a country|Location helps start a practical sourcing conversation.|Select the country relevant to your profile.|Explain delivery coverage separately in your introduction.|Do not assume the country field guarantees worldwide fulfilment.
Merchant identity|Your merchant role remains visible even before your business profile is complete.|Open the public member page.|Check that it identifies you as a merchant.|Add business details to make the profile more useful.
Buyer introduction|Explain your sourcing interests without exposing recipient information.|Mention the types of gifting projects you manage.|Describe useful categories or regions.|Keep employee names and delivery lists private.
Business name|Use the name buyers will recognise in conversations.|Enter the correct business name in the merchant form.|Keep it consistent with your trade deck.|Explain any trading-name difference when quoting.
Business description|Describe the offer in practical terms.|State your main product types.|Mention capabilities you can actually provide.|Avoid unsupported claims about stock, certification, or delivery.
Business category|Choose the closest category for your business.|Review the available category choices.|Select the option that best describes your core offer.|Use your description to explain a specialist niche.
Business website|A website can give buyers more context.|Use a complete website address with its protocol.|Check that it opens the intended business site.|Leave it blank if you do not have a suitable website.
Public profile link|Share the member page when introducing yourself.|Find your account in Connect.|Open the profile and copy its page address.|Check the page contains only information you intend to share.
Preview public information|Review your profile from a visitor's perspective.|Open the member link in a signed-out browser window.|Check the introduction and picture.|Review any publicly viewable PDF as well.
Missing business details|An incomplete merchant profile still appears in the directory.|Add the business information you already have.|Avoid placeholder prices or made-up capabilities.|Return later to complete the remaining accurate details.
Trade-deck status on a profile|Merchant pages explain when no deck has been uploaded.|Look for the Trade deck section.|Open the PDF if one is available.|Ask the merchant for missing capability information before deciding.
Approval labels|A label should be read alongside the underlying product information.|Check which part of the profile the label describes.|Read the deck and product description.|Confirm your project's requirements directly with the merchant.
Profile contact details|Public business information and private account details serve different purposes.|Use public contact details only when you intend them to be visible.|Keep login credentials and private notes out of the bio.|Review contact details embedded in your deck.
Update an outdated profile|Keep the introduction aligned with your current offer.|Remove capabilities you no longer provide.|Update location or branding when relevant.|Check recent conversations for promises that need clarification.
Find your profile in Connect|Search uses visible member information.|Search your displayed name.|Try a relevant country or introduction keyword.|If an active account remains missing, contact support with the member link.
`),
section('Community', '/community', 'Published posts, like counts, and published comments are viewable by visitors. Creating posts, liking, and commenting require a signed-in account. Use real experiences and do not post private recipient information.', `
Read the feed|The feed brings together merchant updates and buyer requests.|Open Home in the community.|Read the topic and author before responding.|Open the member profile for more context.
Write a useful post|Make the purpose clear in the first sentence.|State the offer, question, or request.|Add relevant quantities or timing where useful.|Review the public text before publishing.
Choose a post topic|A relevant topic gives readers useful context.|Choose the topic closest to your subject.|Keep the post focused on that subject.|Explain specialist terms for readers outside your industry.
Add a post photo|Use a photo that supports the text.|Choose an image you have permission to share.|Upload it through the post control.|Wait for upload confirmation before publishing.
Like a post|A like records your own interest or appreciation.|Sign in to your account.|Tap Like on the post.|Check that the control changes to Liked and the count updates.
Remove your like|You can reverse your own reaction.|Find the post showing Liked.|Tap Liked once.|Wait for the count and button to return to the unliked state.
Read like counts|Counts describe saved reactions rather than orders or endorsements.|Look at the count below the post.|Refresh if another person's recent reaction is not visible yet.|Do not interpret likes as a promise to buy.
Likes while signed out|Visitors can see counts but need an account to react.|Tap Like if you want to participate.|Follow the sign-in prompt.|Return to the post and submit your reaction.
Read comments|Comments add public context to a post.|Open Comment on the post.|Read the existing answers before asking again.|Check the author when relying on a commercial statement.
Write a comment|Keep your reply relevant and within the comment limit.|Sign in and open the comments.|Write a clear reply of up to 1,500 characters.|Send once and wait for it to appear.
Comments while signed out|Visitors may read published comments.|Open the comment section to browse replies.|Sign in before submitting a new reply.|Keep personal details out of the public discussion.
Ask for product details|A precise question is easier to answer.|Reference the product or image in the post.|Ask about one concrete requirement such as size or branding.|Move private delivery information into a direct conversation.
Reply as a merchant|Give buyers facts they can use to compare options.|Answer the requested quantity and timing first.|Distinguish confirmed details from estimates.|Offer a private follow-up for a tailored quotation.
Post a buyer request|Explain the project without publishing sensitive recipient details.|State the occasion, quantity, and destination region.|Include a realistic arrival deadline and budget basis.|Ask merchants to explain relevant options and constraints.
Post a product update|A community update should match what you can actually supply.|Describe the product accurately.|State when an image shows a sample or custom option.|Direct interested buyers to the product or your profile.
Share a post|The Share action provides a link to the conversation.|Open Share beneath the post.|Use the device sharing sheet or copied link.|Send the link with enough context for the recipient.
Public conversation etiquette|Useful discussion is relevant, respectful, and factual.|Respond to the question actually asked.|Avoid repeated promotional replies across unrelated posts.|Correct outdated information when someone flags it.
Avoid duplicate submissions|Repeated taps can create confusion when a request is slow.|Wait while an action shows it is saving.|Check the post or comments before trying again.|Retry only if the first attempt did not save.
Report a community problem|Give support enough context to investigate a specific item.|Copy the post or member link.|Describe the problematic content and where it appears.|Keep evidence private when it contains personal information.
Refresh stale activity|Counts may change as other members interact.|Allow the feed time to refresh.|Reload the page if the displayed result remains stale.|Check your signed-in state before repeating a write action.
`),
section('Member directory', '/connect', 'The member directory lets signed-in people follow active GiftGrid accounts and start private conversations. Public profile details never include account email.', `
Discover people|Connect shows active community accounts.|Browse the directory.|Use search to narrow the results.|Open profiles before starting a conversation.
Search members|Search works best with visible profile details.|Try a display name first.|Use a country or bio keyword if needed.|Clear the search to return to the full directory.
Review a member profile|Member profiles provide public context about a person or merchant.|Open Members from the community navigation.|Search for the displayed name or country.|Open the profile and review the public details.
Understand member visibility|The directory lists active accounts independently of merchant deck status.|Open Members.|Search for a name or location.|Open a public profile to see available business information.
Browse all members|The directory shows active community accounts.|Open Members.|Clear the search field to see all available results.|Use the profile link to read more.
Read member details|Public profile details introduce a community member.|Read their displayed name and introduction.|Check the member role and country if shown.|Treat the profile as context rather than proof of a commercial claim.
Review a post author|A public post can introduce you to its author.|Read the post in context.|Open the author profile if you need more public information.|Use community posts or comments for relevant public discussion.
Use public community discussion|Community posts and comments are the available shared discussion space.|Write a question that is relevant to the wider community.|Avoid sharing private contact, delivery, or recipient information.|Keep the discussion respectful and useful to readers.
Find public conversations|Community posts and their comments are visible discussion threads.|Open the community feed.|Read the post before adding a comment.|Use the post link to return to a useful public discussion.
Introduce a gifting project publicly|A concise public post can explain a sourcing need to the community.|Describe the recipient group in general terms.|Include approximate quantity, destination region, and deadline.|Keep employee names and individual addresses out of the post.
Update a public request|A useful comment adds new information to an existing public request.|Open the relevant post.|State what has changed or what detail remains unclear.|Avoid repeated comments that add no useful information.
Keep public posts appropriate|Public posts and comments can be read by other community members.|Keep questions relevant to the community topic.|Do not include private order, recipient, or login information.|Move sensitive business details to a channel you arrange outside GiftGrid.
Check a public profile|A profile can help distinguish members with similar names.|Open the profile from the member directory.|Compare the displayed name, role, and public business details.|Do not post private details when asking the community for help.
No public answer yet|A public post does not guarantee an immediate reply.|Check that your question is clear and includes relevant project context.|Allow time for members in different time zones.|Browse the directory for other relevant public business profiles.
Browse without ordering|Reading a profile or product page does not create a purchase.|Use the member directory to learn who is listed.|Open Shop separately to review available product details.|Confirm availability and commercial terms before making an order.
Member directory problems|A directory loading error may be temporary.|Check your internet connection.|Retry the member page once.|Record the page and visible error if the problem continues.
`),
section('Merchant products', '/dashboard/listings', 'Merchant listings and community posts are different. A post does not automatically become a shop product. Listing status and trade-deck eligibility both affect shop visibility; a saved draft is not a live listing.', `
Prepare a listing|Gather product facts before opening the listing form.|Confirm the title, category, and description.|Prepare an accurate product photograph.|Check your minimum order and fulfilment assumptions.
Product titles|Use a title that identifies the actual item.|Name the product type and useful distinguishing feature.|Avoid keyword repetition and unsupported superlatives.|Keep variant details consistent with the description.
Short descriptions|The short description should explain the offer quickly.|State what the item is and who it suits.|Mention the most important material or format.|Leave detailed terms for the full description and quotation.
Full descriptions|Give buyers enough context to ask an informed question.|Describe materials, dimensions, and included items.|Explain relevant options and limitations.|Remove claims you cannot substantiate.
Choose a product category|The category helps buyers browse relevant offers.|Select the closest available category.|Check that the title and image support that choice.|Explain a specialist product in the description.
Minimum order quantity|State the smallest order you can support for the offer.|Confirm the quantity with your fulfilment team.|Use a positive whole number in the listing.|Explain whether custom branding requires a different minimum.
Product photos|Show the item buyers will actually receive.|Use a clear image with accurate proportions and colour.|Avoid images you do not have permission to reuse.|Explain if accessories or packaging shown are not included.
Packaging information|Packaging can materially change a gifting proposal.|Describe the standard packaging.|Identify optional gift wrapping or branded packaging.|Confirm the final packaging specification in the quotation.
Product dimensions|Dimensions help buyers assess suitability and shipping.|Measure the actual product rather than estimate from a photo.|Include units and relevant package dimensions.|Confirm packed weight when requesting shipping prices.
Material information|Material details support informed product selection.|List the known main materials.|Separate verified facts from supplier claims.|Provide supporting documentation when a buyer requests it.
Colour options|Help buyers understand which colours are actually available.|Name the available options.|Explain whether photos show every option.|Confirm stock for the selected colour before accepting a deadline.
Branding options|Customisation should have a clearly defined scope.|Describe supported branding methods.|Explain artwork requirements and proof approval.|Confirm branding cost and production time separately.
Sample requests|Samples help resolve questions before a bulk order.|Agree which sample represents the proposed product.|Confirm sample price and shipping.|Explain whether a branded sample differs from final production.
Lead times|Separate preparation, production, and shipping time.|Estimate each stage from current capacity.|Identify what starts the production clock.|Confirm dates after artwork and order details are approved.
Stock availability|Avoid implying stock is reserved by a listing.|Check available quantity when a buyer enquires.|Explain any made-to-order component.|Confirm availability again before the order is agreed.
Save a product draft|A saved product may still need review before appearing in the shop.|Complete the available listing fields.|Save once and check the result.|Read the displayed status before sharing a shop link.
Listing review|Review status is separate from your community profile.|Open the listing dashboard.|Check whether the product is pending or published.|Resolve missing information and contact support about review questions.
Published but missing|A published status alone may not satisfy every visibility condition.|Check the merchant trade-deck requirement.|Check whether a shop category filter excludes the item.|Open the product link or contact support with its identifier.
Edit product information|Keep saved product details aligned with your current offer.|Open the listing in your dashboard.|Update inaccurate text or images.|Review the saved status and public result after editing.
Retire an unavailable offer|Do not continue promoting something you cannot supply.|Use the available listing controls to stop presenting the old offer.|Tell active buyers if their quotation is affected.|Contact support if you need help removing a public product.
Product price discussions|A quote should identify what its price includes.|State the quantity and currency.|Separate product, branding, packaging, and delivery charges.|Confirm validity and exclusions in writing.
Merchant versus supplier products|External supplier cards do not belong to your merchant account.|Check the source shown on the product.|Manage your own listings in the merchant dashboard.|Do not claim ownership of another supplier's offer.
Product and profile consistency|Matching information builds a clearer buying conversation.|Compare your listing with your trade deck.|Correct differences in branding, capabilities, or minimums.|Explain any product-specific exceptions to the buyer.
Listing troubleshooting|Collect evidence before asking support about a product.|Record the product identifier and displayed status.|Check that recent edits saved.|Describe the expected shop result and actual result.
`),
section('Trade decks', '/dashboard/profile', 'A trade deck is a PDF introducing a merchant and its capabilities. Uploads are PDF-only and up to 10 MB. New uploads require super-admin review. Any visitor can view an approved deck from the merchant public profile. Buyers do not need to upload a deck. Merchants are expected to upload one when selling — it shows buyers what they are buying.', `
Upload a trade deck|Prepare a concise presentation, export it as a PDF and use the merchant profile upload control.|Include the business name, product examples, and capabilities.|Choose a real PDF no larger than 10 MB.|Wait for submission confirmation and check the review status in your profile.
Replace an outdated deck|Upload a current version when the offer materially changes.|Review prices, contact details, and capabilities in the source file.|Export the revised PDF and upload it.|Check the public viewer opens the intended current document.
View a merchant deck|Anyone can read an approved deck on its merchant profile.|Open the merchant directory or a merchant profile link.|Choose View trade deck when an approved PDF is available.|Remember that commercial details still need direct confirmation with the merchant.
Trade-deck upload problems|File format, size, and connection problems can interrupt uploads.|Confirm the file is a real PDF under 10 MB.|Retry once on a stable connection and wait for confirmation.|If it still fails, give support the error without publishing private file contents.
`),
section('Buyer sourcing', '/dashboard', 'These guides help you prepare and compare a corporate gifting project. They are planning guidance, not claims that GiftGrid supplies checkout, payments, shipment tracking, or order guarantees. Agree commercial terms directly with the seller.', `
Define a gifting brief|Write down the decision you need suppliers to help you make.|Name the occasion and recipient group.|State quantity, destination, and deadline.|Separate essential requirements from preferences.
Choose a gifting purpose|The purpose should guide the product choice.|Decide whether the gift welcomes, thanks, celebrates, or recognises.|Describe the desired recipient experience.|Use that purpose to reject unsuitable options.
Estimate recipient numbers|Quantity affects pricing, minimum orders, and fulfilment.|Start with the confirmed recipient count.|Allow for agreed extras or replacements.|Tell suppliers which part of the quantity is still provisional.
Set a budget basis|A number is useful only when its inclusions are clear.|State the currency and whether the budget is per gift or total.|Decide whether packaging and delivery are included.|Ask for taxes and exclusions to be itemised.
Build a realistic timeline|Work backwards from the date gifts must arrive.|Allow time for sourcing and sample review.|Include artwork approval and production.|Confirm a delivery margin with the seller.
Choose destination regions|Destination details affect availability and landed cost.|List countries or regions before sharing individual addresses.|Ask whether the supplier serves each destination.|Request separate assumptions for cross-border delivery.
Employee welcome gifts|Choose practical items that suit new starters.|Consider how and where employees will use the gift.|Check remote-delivery and office-distribution needs.|Avoid collecting unnecessary personal information in public requests.
Client appreciation gifts|Match the gift to the relationship and recipient context.|Check your organisation's gifting rules.|Choose an appropriate value and message.|Confirm that the recipient can accept the gift.
Event gifting|Event deadlines require a clear delivery plan.|Confirm attendance and distribution method.|Specify the venue's delivery window.|Plan storage and on-site handling before choosing bulky items.
Seasonal gifting|Seasonal projects need early availability checks.|Confirm the recipient list and budget early.|Ask suppliers about peak-period lead times.|Agree the last acceptable delivery date explicitly.
Recognition gifts|Recognition should connect the gift to the achievement.|Define what is being recognised.|Choose a useful, appropriate item and message.|Check spelling on any personalised content before approval.
Remote team gifts|Distributed teams may need several fulfilment approaches.|Group recipients by destination region.|Compare local supply and international shipping.|Agree how addresses will be collected securely.
Inclusive gifting choices|Recipient suitability matters more than a generic popular choice.|Consider dietary, accessibility, and cultural needs.|Offer a suitable alternative when possible.|Ask for relevant product details without making assumptions about recipients.
Food and drink gifts|Food gifts need accurate ingredient and handling information.|Request ingredient and allergen details from the seller.|Check storage requirements and shelf life.|Confirm recipient suitability and destination restrictions before ordering.
Wellbeing gifts|Avoid unsupported health claims when selecting gifts.|Assess the product's practical use.|Ask for relevant ingredients or safety information.|Do not promise medical benefits to recipients.
Branded merchandise|Branding should support a useful recipient experience.|Choose where and how the logo appears.|Provide approved artwork to the supplier.|Approve a proof before production starts.
Compare quotations|Compare offers using the same quantity and specification.|Separate product, branding, packaging, and delivery costs.|Check lead times and validity dates.|Record exclusions before choosing the lowest headline price.
Shortlist merchants|Use evidence relevant to your project.|Read profiles, decks, and product descriptions.|Ask each merchant the same essential questions.|Keep notes on confirmed capabilities and unanswered points.
Review a sample|A sample review should test the proposed specification.|Compare materials, dimensions, finish, and packaging.|Check branding against the approved artwork.|Record changes that must appear in the final order.
Agree final specifications|Resolve ambiguity before committing to production.|Confirm the exact item, variant, and quantity.|Approve branding, packaging, and delivery details.|Keep a written version of the agreed specification.
Recipient data handling|Keep recipient information out of public sourcing conversations.|Collect only information needed for fulfilment.|Agree who will receive and use the address list.|Use an appropriate private transfer method.
Close a sourcing conversation|Give suppliers a clear outcome when your decision is made.|Tell the selected supplier what remains to be agreed.|Let other shortlisted suppliers know the project status.|Keep the final quotation and specification for reference.
`),
section('Market', '/market', 'The shop combines eligible merchant listings with genuine external supplier entries when an authorised catalog is available. External cards identify their source and link to that supplier. Prices, availability, shipping, and purchase terms must be confirmed at the source.', `
Browse categories|Categories help narrow a broad catalog.|Open the category controls in Shop.|Select a category relevant to your brief.|Clear the filter if you want to compare a wider range.
Open a product|The product page gives more context than its card.|Select the product title or card.|Read the description and source information.|Use the appropriate enquiry or supplier link.
Understand product sources|Merchant listings and external offers have different next steps.|Look for the supplier or merchant identity.|Use the merchant enquiry path for a GiftGrid merchant.|Use the named supplier link for an external product.
Request a merchant quote|A quote request needs enough information to price the project.|Open the merchant product.|Follow its enquiry action.|Provide quantity, destination, deadline, and any branding requirement.
Visit an external supplier|External supplier links take you away from GiftGrid.|Check the named supplier on the product page.|Open the source link.|Confirm the current product, seller, and terms before ordering there.
AliExpress products|AliExpress entries are shown only when genuine product data has been added.|Read the product source and original link.|Confirm the seller, selected variant, and current price on AliExpress.|Check shipping and buyer terms on the supplier's site.
Faire products|Faire entries refer to the named external product source.|Open the product's Faire link.|Check account eligibility and current commercial terms there.|Confirm minimums, stock, and delivery before purchasing.
Unknown product prices|An unavailable price should not be treated as free.|Look for a quote action or source link.|Ask for the price at your required quantity.|Confirm currency and additional costs.
Read price currencies|A displayed price must be interpreted with its currency.|Check the currency next to the price.|Ask whether your quotation uses the same currency.|Confirm the payment amount and terms with the seller.
Minimum quantities in the shop|Minimum quantities may differ between standard and customised offers.|Read any minimum shown on the product.|Ask about your specific variant or branding.|Confirm the final quantity in the quotation.
Unknown availability|A visible product does not guarantee immediate stock.|Read any availability note.|Confirm stock for the exact quantity and variant.|Do not commit to an arrival date based on the card alone.
Supplier data freshness|External product information can change after it is imported.|Check the supplier information date when shown.|Open the original page for current details.|Confirm a quote before making a purchase decision.
Out-of-stock supplier items|Known out-of-stock supplier entries are excluded from the current catalog.|Try another suitable product or merchant.|Confirm stock directly when an item reappears.|Avoid relying on an old saved screenshot.
Stale supplier entries|Old imported entries are hidden rather than presented as current.|Use current shop results for discovery.|Check the original supplier page for a saved item.|Request a current quotation before proceeding.
Product images and variants|One image may not represent every option.|Read the product description alongside the image.|Confirm colour, size, and included accessories.|Request a sample if appearance is important.
Shipping is separate|A product listing is not a delivery promise.|Ask for shipping cost to your destination.|Confirm dispatch timing and estimated transit.|Agree who handles any cross-border requirements.
Supplier purchase terms|External purchases are governed by the seller and platform used.|Read the original product and checkout terms.|Check returns, cancellation, and payment conditions.|Keep the supplier's order confirmation.
Empty shop results|An empty result can reflect a filter or unavailable eligible products.|Clear the category filter.|Browse merchants and ask about your brief.|Do not assume an empty result means no community members can help.
Unavailable product links|A removed or invalid product may return a not-found page.|Return to Shop and search the current catalog.|Ask the merchant about the product if you know its source.|Avoid relying on a saved price from an unavailable page.
Report inaccurate product details|Specific corrections help keep discovery useful.|Copy the GiftGrid product link.|Identify the inaccurate field and current source information.|Contact support without claiming the correction is already applied.
`),
section('Merchant workflow', '/dashboard/workflow', 'The workflow area helps merchants track available profile, listing, and enquiry tasks. It does not independently guarantee a sale, send a quotation, or complete an order. Confirm the result in the relevant product or conversation.', `
Open your workflow|Use the workflow view to see current merchant tasks.|Sign in to your merchant account.|Open Workflow from the dashboard.|Read each task before choosing what to address first.
Complete business setup|An incomplete business profile can leave an onboarding task open.|Review your business information.|Save the required accurate details.|Return to Workflow to check the task state.
Improve incomplete listings|Missing product information can create a listing task.|Open the referenced product.|Add the missing image or description.|Save and check whether the task resolves.
Respond to enquiries|A useful response answers the buyer's actual brief.|Read the quantity, destination, and timing.|Ask for any essential missing detail.|Reply in the relevant conversation and check the workflow afterwards.
Mark work in progress|Use the task status to reflect work you are actually doing.|Open the relevant task.|Choose the available in-progress status.|Finish the underlying work before treating it as complete.
Understand resolved tasks|A task can stop appearing after its underlying issue is fixed.|Check the profile or listing change saved.|Refresh the workflow view.|Confirm the business result rather than relying only on a status label.
Prioritise a deadline|Handle tasks according to real project needs.|Identify any buyer deadlines.|Separate quick missing-information fixes from longer work.|Tell the buyer if a requested date cannot be met.
Keep task context|Use the linked business record when deciding what to change.|Read the task title and details.|Open the referenced profile, listing, or enquiry.|Avoid editing an unrelated product with a similar name.
Workflow access|Merchant workflow tools belong to the signed-in merchant.|Use your own merchant account.|Do not expect buyer accounts to have merchant task access.|Contact support if the wrong role is attached to your account.
Tasks after an edit|A task list can lag behind an edit while it refreshes.|Wait for the save confirmation.|Reload Workflow once.|Report a persistent task with the affected product identifier.
Workflow is not publication|Completing a task does not override product review or deck requirements.|Check the listing's status.|Check trade-deck eligibility separately.|Open the shop to confirm actual visibility.
Workflow troubleshooting|A reproducible example makes task problems easier to diagnose.|Record the task and underlying listing or enquiry.|Note the action that should have changed it.|Send support the visible error or unexpected state.
`),
section('Developer reference', '/console', 'The developer console supports app records, scoped API keys, and webhook registration. Registration does not mean webhook delivery is enabled. No isolated sandbox, published quota system, or generic /api/v1 API is documented here. Keep secret credentials on trusted servers.', `
Developer console overview|Use the console to manage supported integration records.|Sign in with an account allowed to use the console.|Create or select an app.|Use only routes and controls available in the current console.
App records|An app record identifies an integration you manage.|Give the app a clear name and purpose.|Check the saved record belongs to your account.|Keep unrelated integrations in separate records where appropriate.
Create an API key|A key grants the scopes selected when it is created.|Choose the app and minimum required permissions.|Store the returned secret in your secret manager.|Do not paste the secret into public documentation.
API key authentication|Protected developer requests accept a bearer key.|Read the secret from a server-side environment variable.|Send it in the Authorization header.|Keep request logs from recording that header.
Choose key scopes|A key should have only the permissions its job requires.|Use apps:read for reading app records.|Add apps:write, keys:write, or webhooks:write only when needed.|Create a separate key for a different responsibility.
Key expiry|Expired keys cannot continue to authorise requests.|Choose an expiry suitable for the integration.|Record a renewal date privately.|Replace the key before scheduled work depends on it.
Revoke an API key|Revocation stops future use of a key.|Identify the key record in the console.|Revoke it using the available control.|Check dependent integrations use a replacement where necessary.
Rotate a secret|Rotation should avoid leaving old credentials active indefinitely.|Create a replacement with the required scopes.|Update the consuming service and verify access.|Revoke the old key after the replacement works.
Read app records|The app API returns records for the authenticated owner.|Use GET /api/developer/apps with an authorised key.|Check the HTTP status before reading the response.|Do not assume another account's records are accessible.
Register a webhook|Registration stores an endpoint configuration; delivery is not active.|Use a valid HTTPS endpoint you control.|Choose the supported event names shown by the console.|Do not build a production dependency on receiving deliveries yet.
Check service health|The health endpoint is a public connectivity check.|Request GET /api/health.|Check the HTTP status and response body.|Test your specific authenticated workflow separately.
Read the shop API|The public shop endpoint exposes the current visible catalog.|Request GET /api/shop.|Use category and page query parameters when needed.|Handle an empty products array as a valid result.
Read community posts|Published community content is available through the public feed route.|Request GET /api/community/posts.|Treat returned text as untrusted display content.|Keep private account information out of downstream public displays.
Handle API errors|Use status codes and the returned error message to guide recovery.|Check authentication when a request returns 401.|Check permissions when it returns 403.|Show a useful message without exposing secret request details.
Retry reads carefully|Temporary failures do not justify unlimited retry loops.|Use a finite request timeout.|Retry safe reads with increasing delays.|Stop and surface the failure after a bounded number of attempts.
Protect integration secrets|Client bundles and repositories are not secret stores.|Keep API keys in a server-side secret manager.|Exclude local environment files from version control.|Rotate any key that was exposed.
Integration release checks|Verify the actual routes your integration uses.|Test authentication and the required scopes.|Handle missing data and non-success responses.|Confirm the integration does not depend on unavailable sandbox or webhook features.
Current capability boundaries|Documentation should distinguish implemented controls from planned services.|Use app and key management where available.|Treat webhook registration as configuration only.|Ask support before relying on a feature without a documented working route.
`),
section('CLI', '/console', 'The CLI is provided in the GiftGrid source repository as scripts/giftgrid-cli.mjs. It uses Node.js built-in APIs. Run it from the project folder; on Windows PowerShell, npm.cmd can be used if execution policy blocks npm.ps1. Never put API secrets directly in command arguments.', `
Run the CLI|Start with a public health request to check connectivity.|Open a terminal in the GiftGrid repository.|Run npm run giftgrid -- status.|Read the JSON result or reported connection error.
Read the catalog from the CLI|Use the shop command to inspect visible catalog data.|Run npm run giftgrid -- shop list.|Add --category and --page when needed.|Treat an empty catalog as a valid response rather than creating placeholder products.
Read the feed from the CLI|The community list command reads published posts.|Run npm run giftgrid -- community list.|Inspect the returned post identifiers and public fields.|Avoid copying private credentials into saved terminal output.
Authenticate CLI app management|Protected app commands need a developer key in the environment.|Set GIFTGRID_API_KEY through your trusted shell or secret manager.|Run npm run giftgrid -- apps list with an apps:read key.|Remove temporary credentials from the shell when finished.
`),
section('Images and files', '/dashboard/profile', 'Upload only files you own or are allowed to share. Public profile pictures, community photos, and trade decks may be visible to visitors. Wait for the upload response before assuming a file is available.', `
Prepare a product image|Use an image that accurately represents the product.|Photograph the actual item in clear light.|Remove unrelated private information from the frame.|Check that the item remains legible on a small screen.
Image reuse permission|Finding an image online does not establish permission to reuse it.|Check who owns the image.|Obtain appropriate permission before uploading.|Keep the source and licence information privately.
Photograph packaging|Packaging images should show what the offer includes.|Photograph the standard configuration.|Label optional ribbons, inserts, or boxes in the description.|Avoid implying a premium package is included by default.
Photograph a variant|Make differences between variants understandable.|Use an image of the actual colour or size where possible.|Name the variant in the product text.|Explain any difference between the photo and available stock.
Avoid personal data in photos|Photos can reveal information beyond the product.|Check labels, screens, addresses, and faces in the frame.|Remove or obscure information you should not publish.|Review the final upload preview.
Choose a profile image|A profile picture should be recognisable at small sizes.|Use a clear portrait or legitimate brand image.|Keep important details near the centre.|Check the displayed result after saving.
Upload a community photo|Attach a relevant image to support a post.|Use the photo upload control in the composer.|Wait for the upload to finish.|Review both image and text before publishing.
PDF readability|A deck should remain readable on a phone.|Use clear headings and readable text sizes.|Export text cleanly rather than using blurry screenshots.|Open the PDF on another device before uploading.
Reduce a PDF size|Keep the deck within the 10 MB upload limit.|Compress oversized photos in the source presentation.|Export with suitable PDF image quality.|Check that text and product detail remain readable.
File upload connection errors|A network interruption can leave an upload unfinished.|Read the visible error or progress state.|Check your connection and retry once.|Confirm the resulting file opens before closing the page.
Check the public file|A successful upload should be verified at its destination.|Open the public profile or post.|Check the image or PDF is the intended version.|Correct the source file if private or outdated information remains.
Replace a wrong image|Correct an inaccurate image where the relevant edit control is available.|Choose the intended replacement file.|Save and wait for confirmation.|Contact support if the public content has no suitable edit control.
`),
section('Help', '/contact', 'Support can investigate a specific page, account-access problem, or failed action. Include the route, time, and visible error. Do not send passwords, API keys, access tokens, or entire recipient lists.', `
A page will not load|Separate a local connection problem from a repeatable site error.|Check another page on the site.|Reload the affected page once.|Record the URL and error if it still fails.
A button appears disabled|Disabled controls often indicate missing input or an action in progress.|Read nearby instructions.|Complete the required selection or field.|Wait for an active save to finish before trying again.
A like did not save|The saved server result determines your reaction.|Check that you are signed in.|Reload the post and inspect Like or Liked.|Retry once only if the intended reaction is absent.
A comment did not appear|A slow or failed request should be checked before resending.|Keep a copy of your comment text.|Reopen the comments and look for the saved reply.|Retry if it is absent and the error is resolved.
A follow did not save|Check the saved following list rather than repeatedly tapping.|Sign in and open Connect.|Select Following to verify the member.|Retry from the member card if the follow is missing.
A message failed|Keep private message content out of public troubleshooting posts.|Check your session and connection.|Reopen the intended conversation.|Contact support with the error and conversation reference if necessary.
A profile seems missing|Active community accounts should appear independently of deck status.|Clear directory search and filters.|Search the displayed name or open the member link.|Contact support if the account still cannot be found.
A product seems missing|Product eligibility differs from member visibility.|Clear the shop category filter.|Check the listing status and deck requirement.|Ask support about the specific product if both appear correct.
A deck will not open|PDF display varies between browsers and devices.|Try the document's open or download link.|Check another PDF-capable browser.|Report the merchant profile link if the file itself is unavailable.
An external supplier link changed|External product pages are controlled by their source platform.|Check the current supplier page.|Do not rely on the old price or stock description.|Report the GiftGrid product link and the observed change.
Report a misleading offer|Describe the discrepancy with enough detail to investigate.|Copy the product or post link.|Identify the specific claim and supporting information.|Send the report privately to support.
Contact support effectively|A concise reproducible report saves follow-up questions.|State what you were trying to do.|Give the page, time, and exact visible error.|Include a redacted screenshot only if it helps explain the problem.
Check whether a change is live|A local edit or announcement is not proof of a production update.|Open the public page in a fresh browser session.|Check the behaviour relevant to the change.|Report the route and result if the expected update is absent.
`),
];

export const communityGuides = docSections.flatMap(section => section.guides);
export function getCommunityGuide(slug: string) { return communityGuides.find(guide => guide.slug === slug); }
