import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getArticle,getArticles } from '@/lib/blog/articles';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=await getArticle(slug);if(!a)return {};return {title:a.title,description:a.excerpt,alternates:{canonical:`/blog/${a.slug}`},openGraph:{type:'article',title:a.title,description:a.excerpt,url:`https://www.degiftgrid.com/blog/${a.slug}`,images:[{url:a.image,alt:a.imageAlt}],publishedTime:a.date}};}
export default async function BlogPostPage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const a=await getArticle(slug);if(!a)notFound();const related=(await getArticles()).filter(p=>p.slug!==slug&&p.category===a.category).slice(0,3);
 const ld={'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.excerpt,datePublished:a.date,image:`https://www.degiftgrid.com${a.image}`,mainEntityOfPage:`https://www.degiftgrid.com/blog/${a.slug}`,author:{'@type':'Organization',name:'GiftGrid'},publisher:{'@type':'Organization',name:'GiftGrid'}};
 return <main className="bg-slate-50"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(ld).replace(/</g,'\\u003c')}}/><article><header className="page-hero relative isolate overflow-hidden bg-slate-950 text-white"><Image src={a.image} alt={a.imageAlt} fill priority sizes="100vw" className="hero-drift object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950/95 via-slate-950/75 to-slate-950/45"/><div className="relative mx-auto max-w-7xl px-6 py-20 lg:px-10 lg:py-28"><Link href="/blog" className="text-sm font-semibold text-blue-100">← GiftGrid Journal</Link><p className="mt-10 text-xs font-bold uppercase tracking-[.18em]">{a.category} · {Math.ceil(a.wordCount/220)} min read</p><h1 className="mt-5 max-w-4xl text-4xl font-medium leading-tight tracking-[-.035em] sm:text-5xl">{a.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/85">{a.excerpt}</p><p className="mt-6 text-xs text-white/70">GiftGrid Editorial · <time dateTime={a.date}>{new Date(a.date+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</time></p></div></header><div className="mx-auto grid max-w-7xl gap-12 px-6 py-14 lg:grid-cols-[230px_minmax(0,760px)] lg:px-10"><nav aria-label="In this article" className="h-fit rounded-xl border border-slate-200 bg-white p-5 lg:sticky lg:top-24"><p className="mb-4 text-xs font-bold uppercase tracking-wider text-slate-500">In this guide</p><ol className="space-y-3">{a.sections.map((s,i)=><li key={i}><a href={`#section-${i+1}`} className="text-sm leading-6 text-slate-600 hover:text-blue-700">{s.heading}</a></li>)}</ol></nav><div className="min-w-0"><p className="text-xl leading-9 text-slate-700">{a.intro}</p><div className="mt-12 space-y-12">{a.sections.map((s,i)=><section key={i} id={`section-${i+1}`} className="scroll-mt-24"><h2 className="text-2xl font-semibold leading-snug text-slate-950 sm:text-3xl">{s.heading}</h2>{s.paragraphs.map((p,j)=><p key={j} className="mt-5 text-base leading-8 text-slate-600 sm:text-lg sm:leading-9">{p}</p>)}</section>)}</div><aside className="mt-14 rounded-2xl bg-blue-50 p-7"><h2 className="text-xl font-semibold">Put your next step into practice.</h2><p className="mt-3 leading-7 text-slate-600">Explore a store review or talk with GiftGrid about your brand and gifting plans.</p><div className="mt-5 flex flex-wrap gap-5"><Link href="/store-review" className="font-semibold text-blue-700">Explore store readiness ↗</Link><Link href="/book" className="font-semibold text-blue-700">Book a conversation ↗</Link></div></aside></div></div></article>{related.length>0&&<section className="mx-auto max-w-7xl px-6 pb-20 lg:px-10"><h2 className="text-2xl font-semibold">Keep reading</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{related.map(p=><Link key={p.slug} href={`/blog/${p.slug}`} className="rounded-xl border border-slate-200 bg-white p-6 font-semibold leading-7 text-slate-800">{p.title} ↗</Link>)}</div></section>}</main>;
}
