import React, {useCallback, useEffect, useState} from 'react';
import {ActivityIndicator, Text, TextInput, View} from 'react-native';

type RequestItem = {id:string;title:string;category?:string;quantity?:number;budget?:string;neededBy?:string;deliveryRegion?:string;customization?:string;details?:string;teaser?:string;created_at?:string};
type ApiClient = {request:(path:string,method?:string,body?:unknown)=>Promise<any>};
const initial = {title:'',category:'Gifts',quantity:'400',budgetMin:'8',budgetMax:'12',currency:'USD',neededBy:'',deliveryRegion:'',customization:'logo',details:''};

export function BuyerRequests({client,session,onSignIn}:{client:ApiClient;session:any;onSignIn:()=>void}) {
  const [requests,setRequests]=useState<RequestItem[]>([]),[canPost,setCanPost]=useState(false),[role,setRole]=useState(''),[form,setForm]=useState(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const result=await client.request('/buyer/requests');setRequests(result.requests||[]);setCanPost(Boolean(result.canPost));setRole(result.role||'');setNotice('');}catch(e:any){setNotice(e.message||'Unable to load requests.');}finally{setLoading(false);}},[client]);
  useEffect(()=>{void load();},[load,session?.user?.id]);
  const submit=async()=>{if(!session){onSignIn();return;}setBusy(true);setNotice('');try{await client.request('/buyer/requests','POST',{...form,quantity:Number(form.quantity),budgetMin:Number(form.budgetMin),budgetMax:Number(form.budgetMax)});setForm(initial);setNotice('Your gifting request is live.');await load();}catch(e:any){setNotice(e.message||'Unable to publish your request.');}finally{setBusy(false);}};
  const field=(label:keyof typeof initial,placeholder:string,keyboardType:any='default',multiline=false)=><TextInput key={label} value={form[label]} onChangeText={value=>setForm(old=>({...old,[label]:value}))} placeholder={placeholder} keyboardType={keyboardType} multiline={multiline} style={[styles.input,multiline&&{minHeight:90,textAlignVertical:'top'}]}/>;
  return <View style={styles.card}><Text style={styles.title}>Gifting requests</Text><Text style={styles.muted}>Post a buyer brief. Signed-in merchants can read full details and respond.</Text>
    {session&&canPost&&<View style={styles.form}><Text style={styles.label}>Post a request</Text>{field('title','Request title')}{field('category','Category (Gifts, Apparel, Wholesale…)')}{field('quantity','Quantity','numeric')}{field('budgetMin','Minimum budget per unit','decimal-pad')}{field('budgetMax','Maximum budget per unit','decimal-pad')}{field('currency','Currency (USD, GBP, EUR)')}{field('neededBy','Needed by (YYYY-MM-DD)')}{field('deliveryRegion','Delivery region')}{field('customization','Customization: none, logo, packaging, personalization, multiple')}{field('details','Describe the gifting request. Keep contact details private.', 'default', true)}<Text onPress={()=>void submit()} style={[styles.button,busy&&{opacity:.55}]}>{busy?'Publishing…':'Publish request'}</Text></View>}
    {!session&&<Text onPress={onSignIn} style={styles.button}>Sign in to post or read merchant briefs</Text>}
    {session&&role==='corporate_buyer'&&!canPost&&<Text style={styles.muted}>Buyer account approval is needed before posting.</Text>}
    {!!notice&&<Text style={styles.notice}>{notice}</Text>}{loading?<ActivityIndicator color="#176b53"/>:requests.map(item=><View key={item.id} style={styles.request}><Text style={styles.label}>{item.title}</Text>{item.teaser?<Text style={styles.muted}>{item.teaser}</Text>:<><Text style={styles.muted}>{item.category} · {item.created_at?new Date(item.created_at).toLocaleDateString():''}</Text><Text style={styles.text}>Quantity: {item.quantity} · Budget: {item.budget} · Needed: {item.neededBy}</Text><Text style={styles.text}>Delivery: {item.deliveryRegion} · Customization: {item.customization}</Text><Text style={styles.text}>{item.details}</Text></>}</View>)}
  </View>;
}
const styles={card:{backgroundColor:'#fff',borderRadius:14,padding:15,borderWidth:1,borderColor:'#e4eae7',gap:10} as const,title:{fontSize:18,fontWeight:'700',color:'#15251e'} as const,label:{fontSize:14,fontWeight:'700',color:'#15251e'} as const,muted:{fontSize:12,lineHeight:18,color:'#718078'} as const,text:{fontSize:13,lineHeight:19,color:'#263b30'} as const,input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d8e2dd',borderRadius:10,paddingHorizontal:12,paddingVertical:10,color:'#15251e'} as const,form:{gap:8,marginTop:8} as const,button:{alignSelf:'flex-start',paddingHorizontal:14,paddingVertical:11,borderRadius:9,overflow:'hidden',backgroundColor:'#176b53',color:'#fff',fontSize:13,fontWeight:'700'} as const,notice:{fontSize:13,color:'#8b4c14',padding:10,backgroundColor:'#fff3df',borderRadius:9} as const,request:{gap:5,borderTopWidth:1,borderColor:'#e4eae7',paddingTop:12,marginTop:3} as const};
